name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: read

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.12.x

    - name: Create Lighthouse CI config
      run: |
        cat > lighthouserc.js << 'EOF'
        module.exports = {
          ci: {
            collect: {
              url: [
                'https://madscie254.github.io/MadScie254/',
                'https://madscie254.github.io/MadScie254/about.html',
                'https://madscie254.github.io/MadScie254/projects.html',
                'https://madscie254.github.io/MadScie254/skills.html',
                'https://madscie254.github.io/MadScie254/education.html',
                'https://madscie254.github.io/MadScie254/news.html',
                'https://madscie254.github.io/MadScie254/contact.html'
              ],
              settings: {
                chromeFlags: '--no-sandbox --headless --disable-gpu',
                // Mobile emulation settings
                emulatedFormFactor: 'mobile',
                throttling: {
                  rttMs: 40,
                  throughputKbps: 10240,
                  cpuSlowdownMultiplier: 1,
                  requestLatencyMs: 0,
                  downloadThroughputKbps: 0,
                  uploadThroughputKbps: 0
                }
              }
            },
            assert: {
              assertions: {
                'categories:performance': ['error', {minScore: 0.9}],
                'categories:accessibility': ['error', {minScore: 0.98}],
                'categories:best-practices': ['error', {minScore: 0.9}],
                'categories:seo': ['error', {minScore: 0.95}],
                'categories:pwa': ['warn', {minScore: 0.8}]
              }
            },
            upload: {
              target: 'temporary-public-storage'
            }
          }
        };
        EOF

    - name: Wait for deployment
      run: |
        echo "Waiting for GitHub Pages deployment to be ready..."
        sleep 60
        
        # Test if the site is accessible
        for i in {1..10}; do
          if curl -s -o /dev/null -w "%{http_code}" https://madscie254.github.io/MadScie254/ | grep -q "200"; then
            echo "Site is accessible"
            break
          else
            echo "Attempt $i: Site not yet accessible, waiting..."
            sleep 30
          fi
        done

    - name: Run Lighthouse CI
      run: |
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-results
        path: .lighthouseci/
        retention-days: 30

    - name: Comment on PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Find the Lighthouse results
          const resultsDir = '.lighthouseci';
          if (fs.existsSync(resultsDir)) {
            const comment = `
            ## 🔍 Lighthouse CI Results
            
            Performance audit completed! Check the uploaded artifacts for detailed reports.
            
            **Quality Gates:**
            - ✅ Performance ≥ 90%
            - ✅ Accessibility ≥ 98%  
            - ✅ SEO ≥ 95%
            - ⚠️ PWA ≥ 80% (warning only)
            
            📊 [View detailed results in the uploaded artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }

    - name: Generate performance summary
      if: always()
      run: |
        echo "## Lighthouse CI Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Quality Gates" >> $GITHUB_STEP_SUMMARY
        echo "- **Performance**: ≥ 90%" >> $GITHUB_STEP_SUMMARY
        echo "- **Accessibility**: ≥ 98%" >> $GITHUB_STEP_SUMMARY
        echo "- **SEO**: ≥ 95%" >> $GITHUB_STEP_SUMMARY
        echo "- **Best Practices**: ≥ 90%" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Pages Tested" >> $GITHUB_STEP_SUMMARY
        echo "- Homepage" >> $GITHUB_STEP_SUMMARY
        echo "- About" >> $GITHUB_STEP_SUMMARY
        echo "- Projects" >> $GITHUB_STEP_SUMMARY
        echo "- Skills" >> $GITHUB_STEP_SUMMARY
        echo "- Education" >> $GITHUB_STEP_SUMMARY
        echo "- FinTech News" >> $GITHUB_STEP_SUMMARY
        echo "- Contact" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📁 Detailed results are available in the uploaded artifacts." >> $GITHUB_STEP_SUMMARY
